### ISSUE TITLE
À explorer: IIIF canvas panel

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/expot-iiif#1]
[Canvas Panel](https://iiif-canvas-panel.netlify.app/) is a [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) that renders a [IIIF Canvas](https://iiif.io/api/presentation/3.0/#53-canvas) and the annotations on it. If you already know what Canvases and Annotations are you are ready to get started. If not, [here's a brief introduction](https://iiif-canvas-panel.netlify.app/about) with links to more learning resources.

Canvas Panel is not a IIIF Viewer, like Mirador or Universal Viewer. It's not a full application - it's a component of your application. On its own, Canvas Panel doesn't render a IIIF Manifest - but it can be used as the rendering surface in any kind of IIIF application you want to build. You can see Canvas Panel used this way in some of the [demo applications](https://iiif-canvas-panel.netlify.app/docs/applications/simple-viewer). It also provides a powerful API for drawing annotations on the canvas and responding to user interaction with the canvas.

**Comment by lenaMK** [comment]
@emchateau peut-être que vous voudrez en discuter avec Emir en préparation du midi-causerie mardi prochain? il n'est pas dans le repo donc je ne peux pas le tagger

**Comment by emchateau** [comment]
Clairement, je lui avais écrit.
Je vais l’attraper sur Teams.
Amitiés,

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau
